export const UPDATE_POST = 'UPDATE_POST';

// login actiontypes
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';
export const SET_AUTH = 'SET_AUTH';

export const EDIT_USER_SUCCESSFUL = 'EDIT_USER_SUCCESSFUL';
export const EDIT_USER_FAILED = 'EDIT_USER_FAILED';

export const PASSWORD_NOT_MATCH = 'PASSWORD_NOT_MATCH';
export const USER_PROFILE_SUCCESSFUL = 'USER_PROFILE_SUCCESSFUL';
export const USER_PROFILE_FAILURE = 'USER_PROFILE_FAILURE';

export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';

export const FETCH_FRIENDS_SUCCESS = 'FETCH_FRIEND_SUCCESS';
export const ADD_FRIEND = 'ADD_FRIEND';
export const REMOVE_FRIEND = 'REMOVE_FRIEND';
